INSERT IGNORE  INTO song_types (id,type, creat_at) VALUES
(1,'Pop', NOW()),
(2,'Rock', NOW()),
(3,'Hip Hop', NOW()),
(4,'Jazz', NOW()),
(5,'Blues', NOW()),
(6,'R&B', NOW()),
(7,'Country', NOW()),
(8,'Classical', NOW()),
(9,'EDM', NOW()),
(10,'Reggae', NOW()),
(11,'Folk', NOW()),
(12,'Metal', NOW()),
(13,'Indie', NOW()),
(14,'Lo-fi', NOW()),
(15,'Latin', NOW());